name: test-workflow

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run JavaScript/TypeScript tests
      run: bun run test

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    
    - name: Build Rust project
      run: cargo build
      shell: bash

    - name: Run Clippy
      run: cargo clippy --workspace --package geometry -- -D warnings
      shell: bash

    - name: Check Formatting
      run: cargo fmt -- --check
      shell: bash

    # Install cargo-tarpaulin
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    # Run tarpaulin to calculate and enforce coverage
    - name: Run Coverage and Enforce Threshold
      run: cargo tarpaulin --fail-under 95
      shell: bash
